### ISSUE TITLE
能否暴露接口获取Message的key

### ISSUE THREAD

**Issue by eJayYoung** [uxcore/uxcore-message#10]
场景：在某个提交操作中，提示了Message，在duration之内，多点几次提交，Message会生成多个。
建议：能否在全局获取Message的key值，据此来判断全局有多少Message。

**Comment by eternalsky** [comment]
这个思路其实有点问题，其实你应该是在提交上去抖，减少几次提交的数量，而不是单纯的减少 Message 的数量。
