### ISSUE TITLE
消息弹出框消失时间计算有误

### ISSUE THREAD

**Issue by caiyongmin** [uxcore/uxcore-message#11]
连续点击消息弹出框出现的问题，复现步骤：

1. 点击一个消息弹出框，接着又点击一次。

仔细观察可以发现，上一个消息弹出框的时间在这次的消息弹出框出现后被重置了，接着又重新计算了消息持续时间。

多次点击以上效果会更明显些。

**Comment by fengsx** [comment]
0.5.0 及以上版本没有复现
