### ISSUE TITLE
如果在Dialog之前调用过Message组件，Dialog显示时，Message的消息会被遮挡

### ISSUE THREAD

**Issue by paseo** [uxcore/uxcore-message#17]
复现方式：
1. 在页面mount一个Dialog组件“DA”，设置为隐藏
2. 调用Message.info
3. 将“DA“设置为显示
4. 调用Message.info 弹出的消息会被组件”DA”遮挡

原因：Message的container是复用的，创建后不会销毁。如果Dialog的container在Message的container之后创建，Message就会被遮挡

**Comment by fengsx** [comment]
可以参考下 https://github.com/react-component/notification 的文档，尝试下利用 getContainer 这个方法去解决。

至于出现顺序的问题，请配合 uxcore-dialog 去解决。
