### ISSUE TITLE
更新到2.0.6 

### ISSUE THREAD

**Issue by isoloist** [uxcore/uxcore-message#18]
调用  Message.loading会报错 messageInstance = Notification.newInstance 没有定义

**Comment by eternalsky** [comment]
能否升级到新版本，目前的最新版本是 0.4.0 的

**Comment by isoloist** [comment]
看了下node_modules下的 package.json
"name": "uxcore-message",
 "version": "0.4.0"
已经是 0.4.0

**Comment by isoloist** [comment]
问题出在项目使用 import from 而 uxcore-message 使用的是 require ，导致出错

**Comment by liaohongze** [comment]
已更新到0.5.0
然后根据官网上示例的写法：
let Message = require('uxcore-message')
......
Message.success('修改成功！')

报错信息：Uncaught (in promise) TypeError: Notification.newInstance is not a function

**Comment by eternalsky** [comment]
报错的各位，可否提供一下自己的 webpack 版本及配置，开发者本地无法复现目前提到的问题。

**Comment by isoloist** [comment]
"rc-notification": "^1.4.0",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-dom": "^15.4.2",
    "uxcore": "0.9.4",
    "uxcore-tools": "0.2.42"

我删除了node_module的内容，重新npm install之后才出现的问题

**Comment by eternalsky** [comment]
@isoloist 你是在 run uxcore-message 组件吗~ 正常使用组件应该不需要你上面那些依赖。

**Comment by isoloist** [comment]
本来是没有这些依赖的，我添加了 "rc-notification": "1.4.0" 这个之后终于可以工作。

**Comment by eternalsky** [comment]
@isoloist npm 和 webpack 的版本，以及 webpack 的配置能贴一下吗
