### ISSUE TITLE
uxcore-message 0.5.2与rc-notification版本不兼容

### ISSUE THREAD

**Issue by paseo** [uxcore/uxcore-message#22]
使用Message.error('abc')，rc-notification会报错： “callback is not a function”。
原因：
rc-notification的Notification.newInstance要求两个参数：properties, callback。其中第二个参数callback也是必须的，实际上uxcore-message在调用rc-notification的Notification.newInstance时，第二个参数缺失。

**Comment by fengsx** [comment]
抱歉，请升级到 0.5.3及以上版本。
