### ISSUE TITLE
与react16相关的兼容性bug

### ISSUE THREAD

**Issue by yusangeng** [uxcore/uxcore-message#29]
![image](https://user-images.githubusercontent.com/9398751/51024694-372dcd80-15c5-11e9-8e5b-4e00062023d8.png)

在react16.4.1这个版本下，如果一个ReactDOM.render函数是在一个DOM节点的click回调中调用的，那么被render的组件中如果有ref回调属性，这个ref回调不会被同步调用，而是异步调用。

而rc-notification正好就是利用了ref这个属性。

反映到本项目中，就是我截图的那个函数，会返回null。

**Comment by jawil** [comment]
fixed
