### ISSUE TITLE
官网给出的cdn没有Message模块

### ISSUE THREAD

**Issue by vincentshow** [uxcore/uxcore-message#4]
官网http://uxco.re/ 的“组件”章节中有Message的示例，按照“开始使用”cdn中给出的路径加载uxcore（http://g.alicdn.com/uxcore/uxcore/0.1.2/uxcore.js） 后，在chrome的console中提示Uxcore.Message为undefined，但是http://uxco.re/static/uxcore.js 这个脚本里却已经打包了message，大神求搞啊

**Comment by eternalsky** [comment]
非常抱歉，一些新组件刚刚上线，因此还未整合到 cdn 中，请等待 0.1.3 版本~

**Comment by vincentshow** [comment]
@eternalsky 0.1.3大概什么时候上线啊，最近在尝试使用uxcore，下周就要汇报决定是否要用了，如果太晚的话，是否可以单独发一个给我呢，至少让我的demo能够跑的通，vincentshow@outlook.com（前端菜鸟，尝试自己打包都失败了），十分感谢

**Comment by vincentshow** [comment]
oo, 刚刚重新下了一份，已经加上去了，感谢，还有一个建议，就是form组件的input是否也能给出一个jsxtype属性来控制input的type，官方示例中缺少一个type=password的组件

**Comment by vincentshow** [comment]
uxcore分组件管理的，那个建议我去uxcore-form提吧，打扰
