### ISSUE TITLE
如何强制关闭已弹出的某个message

### ISSUE THREAD

**Issue by vincentshow** [uxcore/uxcore-message#5]
比如全局显示loading，怎么在数据加载完毕后手动关闭那个message
除了这种$(".kuma-loading").parents(".kuma-message-notice").remove()，还有更优雅的方式么

**Comment by vincentshow** [comment]
不能使用js移除，否则会导致data-reactid错乱，报异常Uncaught Error: Invariant Violation: processUpdates(): Unable to find child 1 of element.暂时只能先hide

**Comment by eternalsky** [comment]
调用 Message.xxx 后的返回值是一个销毁该实例的方法。

**Comment by vincentshow** [comment]
赞
