### ISSUE TITLE
uxcore-message 与 uxcore-dialog 的 z-index 问题

### ISSUE THREAD

**Issue by lpgray** [uxcore/uxcore-message#6]
uxcore-message 的 z-index 是 1000，uxcore-dialog 的也是 1000，在我的项目中发现有重叠，看不到 message 问题，请修复。

**Comment by eternalsky** [comment]
都是 1000，重叠的情况下，后渲染的覆盖在先渲染的东西上面，感觉没什么问题，能否提供你的场景？
http://codepen.io/eternalsky/pen/qZwNVL

**Comment by lpgray** [comment]
无法复现了，close掉先
