### ISSUE TITLE
请问下为什么单组件引入时样式编译出错呢?

### ISSUE THREAD

**Issue by hong26** [uxcore/uxcore-message#8]
错误提示:`ERROR in ./~/kuma-base/core.less Module build failed: variable @grid-columns is undefined
`和`Error: variable @text-primary-color is undefined`  
按照文档说明我已经安装了`kuma-base`和`uxcore-message`,
在组件里面引入了以下样式,但是编译时为什么还是出错?

```
import 'kuma-base/theme/blue.less'
import 'kuma-base/core.less'
import 'uxcore-message/src/Message.less'
```

**Comment by eternalsky** [comment]
这个只是一个例子~ 如果你是用 webpack 引入 less，可以写

```
import '~kuma-base/theme/blue.less'
import '~kuma-base/core.less'
import '~uxcore-message/src/Message.less'
```
